name: "website deploy"

on:
  pull_request:
    branches: [website]
  push:
    branches: [website]
permissions:
  contents: write
  pull-requests: write
jobs:
  deploy-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "node"
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
      - name: "build"
        run: |
          npm run check-build
      - name: "deploy"
        uses: amondnet/vercel-action@v25.2.0 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          # github-token: ${{ secrets.PAT }} #Optional
          # vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
          working-directory: ./example2/dist
          alias-domains: | #Optional
            visual-gestures-dev.vercel.app
